### ISSUE TITLE
Interactive CSS-only accordion & tabs

### ISSUE THREAD

**Issue by niutech** [OrbitCSS/orbitcss#1]
Your [accordion](https://orbitcss.com/documentation/elements/accordion) and [tabs](https://orbitcss.com/documentation/elements/tabs) implementation is static, ie. they don't collapse/change on click. Please make them interactive using only CSS, like in [Surface.css](https://mildrenben.github.io/surface/) or [Picnic CSS](https://picnicss.com/tests).

**Comment by rhysnhall** [comment]
I'd consider adding these as an optional solution. I don't want to force it on people though as I personally don't like how the accordion in Surface.css collapses and a custom JS solution would be much smoother.

**Comment by niutech** [comment]
Both CSS-only and JS solutions use CSS transitions, so they should be equally smooth. If you don't like Surface.css collapsible, you can use any [pure CSS accordion implementation](https://codepen.io/search/pens?q=pure+CSS+accordion).

**Comment by niutech** [comment]
@rhysnhall So you don't want to make it interactive by default?
