### ISSUE TITLE
Sass warns about color value names

### ISSUE THREAD

**Issue by gaelanlloyd** [OrbitCSS/orbitcss#7]
Hi Rhys,

When I pull OrbitCSS into my project Sass gives me a number of warnings like:

```
WARNING on line 40, column 7 of sass/vendor/orbitcss/scss/base/_colors.scss:
You probably don't mean to use the color value `black' in interpolation here.
It may end up represented as #000000, which will likely produce invalid CSS.
Always quote color names when using them as strings (for example, "black").
If you really want to use the color value here, use `"" + nth($color, 1)'.
```

I think the fix is:

```
@each $color in $color-palette {
  &.is-#{nth($color, 1)} {            // Original code
  &.is-#{"" + nth($color, 1)} {       // Change to this
```

From what I can tell, the following files have references that need to be updated:

- /scss/base/_colors.scss
- /scss/elements/_alert.scss
- /scss/elements/_button.scss
- /scss/elements/_progress.scss
- /scss/elements/_tabs.scss
- /scss/elements/_tag.scss

Environment: Sass 3.5.6, Ruby 2.5.5p157, on Debian 10.

I'm only on *day one* of learning Sass, so your thoughts would be really helpful!  I can also send over a PR with my suggested changes if you think they're appropriate.

(It's been a few months but I'm able to spend more time using OrbitCSS again.  When my Sass skills improve I'd be interested in taking a stab at #4.)

Gaelan

**Comment by rhysnhall** [comment]
Hey Gaelan,

That is an interesting warning. At what stage do these warnings appear, and where?

**Comment by gaelanlloyd** [comment]
Immediately on compiling Sass after cloning the repo.  Here's some truncated output, [full output here](https://gist.github.com/gaelanlloyd/8f9798bff253b6cfd28103acb13837f0).

```
orbitcss > sass --watch scss:css --trace --poll
>>> Sass is watching for changes. Press Ctrl-C to stop.
WARNING on line 40, column 7 of scss/base/_colors.scss:
You probably don't mean to use the color value `black' in interpolation here.
It may end up represented as #000000, which will likely produce invalid CSS.
Always quote color names when using them as strings (for example, "black").
If you really want to use the color value here, use `"" + nth($color, 1)'.

WARNING on line 40, column 7 of scss/base/_colors.scss:
You probably don't mean to use the color value `white' in interpolation here.
It may end up represented as #ffffff, which will likely produce invalid CSS.
Always quote color names when using them as strings (for example, "white").
If you really want to use the color value here, use `"" + nth($color, 1)'.
...
...
...
WARNING on line 22, column 11 of scss/elements/_tabs.scss:
You probably don't mean to use the color value `white' in interpolation here.
It may end up represented as #ffffff, which will likely produce invalid CSS.
Always quote color names when using them as strings (for example, "white").
If you really want to use the color value here, use `"" + nth($color, 1)'.

      write css/main.css
      write css/main.css.map
```

**Comment by rhysnhall** [comment]
Thanks for that. This can be resolved by updating the keys in the color map to use double-quotes.
Current:
```
$color-palette: (
  primary: $primary,
  warning: $warning,
  ...
)  !default;
```
Change to:
```
$color-palette: (
  "primary": $primary,
  "warning": $warning,
  ...
)  !default;
```

I actually have a new version of the framework ready to release. It focuses more on the use of CSS variables but still builds with SASS. I'll make the relevant changes there.

**Comment by rhysnhall** [comment]
This has been resolved in the latest version.
